# Generated by Django 3.0 on 2019-12-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191226_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='big_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='medium_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='small_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
