# Generated by Django 2.2.9 on 2019-12-26 13:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191226_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 12, 26, 13, 52, 35, 833264, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to=''),
        ),
    ]
