# Generated by Django 2.2.9 on 2020-01-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191226_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starid', models.CharField(max_length=100, verbose_name='ID Звезды')),
                ('name', models.CharField(max_length=100, verbose_name='Владелец')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('magnitude', models.FloatField(verbose_name='Звездная величина')),
                ('constellation', models.CharField(max_length=100, verbose_name='Созвездие')),
                ('date', models.DateField()),
            ],
        ),
    ]
