# Generated by Django 2.2.9 on 2020-01-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_catalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='constellation',
            field=models.CharField(max_length=100, verbose_name='Constellation'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='magnitude',
            field=models.FloatField(verbose_name='Magnitude'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='starid',
            field=models.CharField(max_length=100, verbose_name='Star ID'),
        ),
    ]
